/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memoria;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author vick4
 */
public class memoriaform extends javax.swing.JFrame {

    public int clicks = 0;

    public int jugadorEnTurno = 1;
    boolean seguirTurno = false;
    public int punteoJugador1 = 0;
    public int punteoJugador2 = 0;

    public int ultimoElementoCliqueado = 0;
    public int elementoAnterior = 0;

    public String ultimaImagenMostrada = "";
    public String imagenAnterior = "";

    // Cartas encontradas
    public boolean carta1 = true;
    public boolean carta2 = true;
    public boolean carta3 = true;
    public boolean carta4 = true;
    public boolean carta5 = true;
    public boolean carta6 = true;
    public boolean carta7 = true;
    public boolean carta8 = true;
    public boolean carta9 = true;
    public boolean carta10 = true;
    public boolean carta11 = true;
    public boolean carta12 = true;

    public int imgCarta1 = 0;
    public int imgCarta2 = 1;
    public int imgCarta3 = 2;
    public int imgCarta4 = 3;
    public int imgCarta5 = 4;
    public int imgCarta6 = 5;
    public int imgCarta7 = 6;
    public int imgCarta8 = 7;
    public int imgCarta9 = 8;
    public int imgCarta10 = 9;
    public int imgCarta11 = 10;
    public int imgCarta12 = 11;

    String[] rutas = {"/imagenes/rompre1.jpg", "/imagenes/rompre1.jpg", "/imagenes/rompe2.jpg", "/imagenes/rompe2.jpg",
        "/imagenes/rompe3.jpg", "/imagenes/rompe3.jpg", "/imagenes/rompe4.jpg", "/imagenes/rompe4.jpg",
        "/imagenes/rompe5.jpg", "/imagenes/rompe5.jpg", "/imagenes/rompe6.jpg", "/imagenes/rompe6.jpg"};

    boolean nuevoJuego = false;

    /**
     * Creates new form memoriaform
     */
    public memoriaform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jugadorDeTurnoTxt = new javax.swing.JLabel();
        punteoJugador1Txt = new javax.swing.JLabel();
        punteoJugador2Txt = new javax.swing.JLabel();
        imag1 = new javax.swing.JLabel();
        imag2 = new javax.swing.JLabel();
        imag3 = new javax.swing.JLabel();
        imag4 = new javax.swing.JLabel();
        imag5 = new javax.swing.JLabel();
        image6 = new javax.swing.JLabel();
        imag7 = new javax.swing.JLabel();
        imag8 = new javax.swing.JLabel();
        imag9 = new javax.swing.JLabel();
        imag10 = new javax.swing.JLabel();
        imag11 = new javax.swing.JLabel();
        imag12 = new javax.swing.JLabel();
        SALIR = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Turno:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jugadorDeTurnoTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jugadorDeTurnoTxt.setText("Jugador 1");
        getContentPane().add(jugadorDeTurnoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 30));

        punteoJugador1Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        punteoJugador1Txt.setText("Jugador 1: 0 puntos");
        getContentPane().add(punteoJugador1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        punteoJugador2Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        punteoJugador2Txt.setText("Jugador 2: 0 puntos");
        getContentPane().add(punteoJugador2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        imag1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag1.setText("jLabel2");
        imag1.setOpaque(true);
        imag1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag1MouseClicked(evt);
            }
        });
        getContentPane().add(imag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, 150));

        imag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag2.setText("jLabel2");
        imag2.setOpaque(true);
        imag2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag2MouseClicked(evt);
            }
        });
        getContentPane().add(imag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 150, 150));

        imag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag3.setText("jLabel2");
        imag3.setOpaque(true);
        imag3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag3MouseClicked(evt);
            }
        });
        getContentPane().add(imag3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 150, -1));

        imag4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag4.setText("jLabel2");
        imag4.setOpaque(true);
        imag4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag4MouseClicked(evt);
            }
        });
        getContentPane().add(imag4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 150, 150));

        imag5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag5.setText("jLabel2");
        imag5.setOpaque(true);
        imag5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag5MouseClicked(evt);
            }
        });
        getContentPane().add(imag5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 150, 150));

        image6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        image6.setText("jLabel2");
        image6.setOpaque(true);
        image6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image6MouseClicked(evt);
            }
        });
        getContentPane().add(image6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 150, 150));

        imag7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag7.setText("jLabel2");
        imag7.setOpaque(true);
        imag7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag7MouseClicked(evt);
            }
        });
        getContentPane().add(imag7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 150, 150));

        imag8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag8.setText("jLabel2");
        imag8.setOpaque(true);
        imag8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag8MouseClicked(evt);
            }
        });
        getContentPane().add(imag8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 150, 150));

        imag9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag9.setText("jLabel2");
        imag9.setOpaque(true);
        imag9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag9MouseClicked(evt);
            }
        });
        getContentPane().add(imag9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 150, 150));

        imag10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag10.setText("jLabel2");
        imag10.setOpaque(true);
        imag10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag10MouseClicked(evt);
            }
        });
        getContentPane().add(imag10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 150, 150));

        imag11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag11.setText("jLabel2");
        imag11.setOpaque(true);
        imag11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag11MouseClicked(evt);
            }
        });
        getContentPane().add(imag11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 150, 150));

        imag12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadadef.jpg"))); // NOI18N
        imag12.setText("jLabel2");
        imag12.setOpaque(true);
        imag12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imag12MouseClicked(evt);
            }
        });
        getContentPane().add(imag12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 150, 150));

        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        SALIR.setContentAreaFilled(false);
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, -1, 50));

        volver.setText("Nuevo Juego");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 100, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memoria/NYAQ3KNWERALBENH75LPKTC3ZM.jpg"))); // NOI18N
        jLabel19.setText("jLabel2");
        jLabel19.setOpaque(true);
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 990, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imag1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag1MouseClicked
        if (noEsPar(1, rutas[imgCarta1], carta1)) {
            voltearCartas();

        } else {
            imag1.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta1])));
        }
    }//GEN-LAST:event_imag1MouseClicked

    private void imag2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag2MouseClicked
        if (noEsPar(2, rutas[imgCarta2], carta2)) {
            voltearCartas();

        } else {
            imag2.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta2])));
        }
    }//GEN-LAST:event_imag2MouseClicked

    private void imag3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag3MouseClicked
        if (noEsPar(3, rutas[imgCarta3], carta3)) {
            voltearCartas();

        } else {
            imag3.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta3])));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_imag3MouseClicked

    private void imag4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag4MouseClicked
        if (noEsPar(4, rutas[imgCarta4], carta4)) {
            voltearCartas();

        } else {
            imag4.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta4])));
        }      // TODO add your handling code here:
    }//GEN-LAST:event_imag4MouseClicked

    private void imag5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag5MouseClicked
        if (noEsPar(5, rutas[imgCarta5], carta5)) {
            voltearCartas();

        } else {
            imag5.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta5])));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_imag5MouseClicked

    private void image6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image6MouseClicked
        if (noEsPar(6, rutas[imgCarta6], carta6)) {
            voltearCartas();

        } else {
            image6.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta6])));
        }         // TODO add your handling code here:
    }//GEN-LAST:event_image6MouseClicked

    private void imag7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag7MouseClicked
        if (noEsPar(7, rutas[imgCarta7], carta7)) {
            voltearCartas();

        } else {
            imag7.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta7])));
        }           // TODO add your handling code here:
    }//GEN-LAST:event_imag7MouseClicked

    private void imag8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag8MouseClicked
        if (noEsPar(8, rutas[imgCarta8], carta8)) {
            voltearCartas();

        } else {
            imag8.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta8])));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_imag8MouseClicked

    private void imag9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag9MouseClicked
        if (noEsPar(9, rutas[imgCarta9], carta9)) {
            voltearCartas();

        } else {
            imag9.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta9])));
        }
    }//GEN-LAST:event_imag9MouseClicked

    private void imag10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag10MouseClicked
        if (noEsPar(10, rutas[imgCarta10], carta10)) {
            voltearCartas();

        } else {
            imag10.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta10])));
        }         // TODO add your handling code here:
    }//GEN-LAST:event_imag10MouseClicked

    private void imag11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag11MouseClicked
        if (noEsPar(11, rutas[imgCarta11], carta11)) {
            voltearCartas();

        } else {
            imag11.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta11])));
        }         // TODO add your handling code here:
    }//GEN-LAST:event_imag11MouseClicked

    private void imag12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imag12MouseClicked
        if (noEsPar(12, rutas[imgCarta12], carta12)) {
            voltearCartas();

        } else {
            imag12.setIcon(new ImageIcon(getClass().getResource(rutas[imgCarta12])));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_imag12MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // iniciojuego Datos = new iniciojuego();
        // Datos.setVisible(true);
        // this.dispose();

        generarAleatorios();
        voltearCartas();
    }//GEN-LAST:event_volverActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
         System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    public void generarAleatorios() {
        clicks = 0;

        jugadorEnTurno = 1;
        seguirTurno = false;
        punteoJugador1 = 0;
        punteoJugador2 = 0;

        ultimoElementoCliqueado = 0;
        elementoAnterior = 0;

        ultimaImagenMostrada = "";
        imagenAnterior = "";

        // Cartas encontradas
        carta1 = true;
        carta2 = true;
        carta3 = true;
        carta4 = true;
        carta5 = true;
        carta6 = true;
        carta7 = true;
        carta8 = true;
        carta9 = true;
        carta10 = true;
        carta11 = true;
        carta12 = true;

        punteoJugador1Txt.setText("Jugador 1: 0 puntos");
        punteoJugador2Txt.setText("Jugador 2: 0 puntos");

        nuevoJuego = true;

        int i = 0, cantidad = 12, rango = 12;
        int arreglo[] = new int[cantidad];
        
        arreglo[i] = (int) (Math.random() * rango);
        for (i = 0; i < cantidad; i++) {
            arreglo[i] = (int) (Math.random() * rango);
            for (int j = 0; j < i; j++) {
                if (arreglo[i] == arreglo[j]) {
                    i--;
                }
            }
        }

        imgCarta1 = arreglo[0];
        imgCarta2 = arreglo[1];
        imgCarta3 = arreglo[2];
        imgCarta4 = arreglo[3];
        imgCarta5 = arreglo[4];
        imgCarta6 = arreglo[5];
        imgCarta7 = arreglo[6];
        imgCarta8 = arreglo[7];
        imgCarta9 = arreglo[8];
        imgCarta10 = arreglo[9];
        imgCarta11 = arreglo[10];
        imgCarta12 = arreglo[11];

    }

    public boolean noEsPar(int elemento, String imagen, boolean activo) {

        elementoAnterior = ultimoElementoCliqueado;
        ultimoElementoCliqueado = elemento;

        imagenAnterior = ultimaImagenMostrada;
        ultimaImagenMostrada = imagen;

        if (elementoAnterior != ultimoElementoCliqueado && activo) {
            clicks++;

            if (clicks == 2) {
                if (imagenAnterior.equals(ultimaImagenMostrada)) {
                    if (jugadorEnTurno == 1) {
                        punteoJugador1++;
                        punteoJugador1Txt.setText("Jugador 1: " + String.valueOf(punteoJugador1) + " puntos");
                        bloquearCarta(ultimoElementoCliqueado);
                        bloquearCarta(elementoAnterior);
                        seguirTurno = true;
                    } else {
                        punteoJugador2++;
                        punteoJugador2Txt.setText("Jugador 2: " + String.valueOf(punteoJugador2) + " puntos");
                        bloquearCarta(ultimoElementoCliqueado);
                        bloquearCarta(elementoAnterior);
                        seguirTurno = true;
                    }
                }
            }
        }

        if (clicks == 3) {
            clicks = 0;
            ultimoElementoCliqueado = 0;
            elementoAnterior = 0;
            ultimaImagenMostrada = "";
            imagenAnterior = "";

            if (jugadorEnTurno == 1 && seguirTurno == false) {
                jugadorDeTurnoTxt.setText("Jugador 2");
                jugadorEnTurno = 2;
            } else if (jugadorEnTurno == 2 && seguirTurno == false) {
                jugadorDeTurnoTxt.setText("Jugador 1");
                jugadorEnTurno = 1;
            }

            return true;
        } else {
            return false;
        }
    }

    public void bloquearCarta(int elemento) {
        switch (elemento) {
            case 1:
                carta1 = false;
                break;
            case 2:
                carta2 = false;
                break;
            case 3:
                carta3 = false;
                break;
            case 4:
                carta4 = false;
                break;
            case 5:
                carta5 = false;
                break;
            case 6:
                carta6 = false;
                break;
            case 7:
                carta7 = false;
                break;
            case 8:
                carta8 = false;
                break;
            case 9:
                carta9 = false;
                break;
            case 10:
                carta10 = false;
                break;
            case 11:
                carta11 = false;
                break;
            case 12:
                carta12 = false;
                break;
        }
    }

    public void voltearCartas() {
        seguirTurno = false;

        if (carta1) {
            imag1.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));
        }

        if (carta2) {
            imag2.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));
        }

        if (carta3) {
            imag3.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));
        }

        if (carta4) {
            imag4.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));
        }
        if (carta5) {
            imag5.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));
        }
        if (carta6) {
            image6.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));

        }
        if (carta7) {
            imag7.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));

        }
        if (carta8) {
            imag8.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));

        }
        if (carta9) {
            imag9.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));

        }
        if (carta10) {
            imag10.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));

        }
        if (carta11) {
            imag11.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));

        }
        if (carta12) {
            imag12.setIcon(new ImageIcon(getClass().getResource("/imagenes/portadadef.jpg")));
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memoriaform.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memoriaform.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memoriaform.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memoriaform.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memoriaform().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel imag1;
    private javax.swing.JLabel imag10;
    private javax.swing.JLabel imag11;
    private javax.swing.JLabel imag12;
    private javax.swing.JLabel imag2;
    private javax.swing.JLabel imag3;
    private javax.swing.JLabel imag4;
    private javax.swing.JLabel imag5;
    private javax.swing.JLabel imag7;
    private javax.swing.JLabel imag8;
    private javax.swing.JLabel imag9;
    private javax.swing.JLabel image6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jugadorDeTurnoTxt;
    private javax.swing.JLabel punteoJugador1Txt;
    private javax.swing.JLabel punteoJugador2Txt;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
